version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/local/src/app
    env_file:
      - .env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    command: bash
